FROM java:8
WORKDIR /
ADD /Users/anchal/2019/dependency-injection-clone/dependency-injection/hello-world/target/hello-world-1.00-jar-with-dependencies.jar hello-world-1.00-jar-with-dependencies.jar
CMD java -jar hello-world-1.00-jar-with-dependencies.jar

